version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Preparing deployment files..."
      - mkdir -p output
      - cp -r * output/
artifacts:
  files:
    - '**/*'
  base-directory: output